version: '3.9'

services:

  adminer:
    image: adminer
    restart: always
    environment: 
            ADMINER_DEFAULT_SERVER: db
            ADMINER_DESIGN: dracula
    ports:
      - 8080:8080

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-datavolume:/var/lib/mysql

  api:
    build: "api/."
    restart: always
    ports:
      - 8000:80
    volumes:
      - rootdata:/root
      - userdata:/home
      - webdata:/var/www/html
    hostname: "api-beta"

volumes:
  my-datavolume:
  webdata:
  userdata:
  rootdata: